#!/bin/bash

set -e -x

export GOPATH=$PWD

deps=$PWD/deps.txt

rm -f $deps

cd src

# Remove all .git folders
dirs=$(find * -type d -name '.git')

for dir in $dirs; do
  # Capture deps info
  echo "$(cd $dir/.. && git rev-parse --short HEAD) $dir" >> $deps

  # Remove .git directory
  rm -rf $dir
done
